services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        APP: web
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      HOSTNAME: 0.0.0.0
    restart: unless-stopped
  docs:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        APP: docs
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
      PORT: 3001
      HOSTNAME: 0.0.0.0
    restart: unless-stopped