services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        APP: web
    ports:
      - "8080:80"
    environment:
      NODE_ENV: production
      PORT: 3000
      HOSTNAME: 0.0.0.0
    restart: unless-stopped
  docs:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        APP: docs
    ports:
      - "8081:80"
    environment:
      NODE_ENV: production
      PORT: 3000
      HOSTNAME: 0.0.0.0
    restart: unless-stopped