// All user-facing naming for the App Access screen lives here so it can be changed in one edit.
export const APP_ACCESS = {
  route: "/settings/app-access",
  title: "App Access",
  description: "Choose which reading apps and catalogs may sign in your patrons and borrow for them.",
  add: "Add an app",
  section: "Apps & readers",
  sectionHelp: "Reading apps and catalogs that use this library.",
  flow: "Reading app → your library (Lenny) → patron signs in",
  empty: "No apps yet. Add the reader or catalog your patrons use so it can sign them in.",
  developersTitle: "Connect an app to this library",
  builtIn: "Built in",
  builtInHelp: "Added automatically by Lenny. Turning it off survives restarts.",
  on: "On",
  off: "Off",
  onLine: "Patrons can sign in with this app.",
  offLine: "This app can't sign anyone in.",
  turnOffTitle: (name: string) => `Turn off ${name}?`,
  turnOffBody: "Patrons signed in through it will need to sign in again.",
  turnOffAction: "Turn off",
  turnedOn: (name: string) => `${name} is on. Patrons will sign in again from scratch.`,
  turnedOff: (name: string) => `${name} is off.`,
  switchLabel: (name: string) => `Let ${name} sign in patrons`,
  summary: (on: number, off: number) =>
    (on === 0 ? "No app can sign in patrons right now" : `${on} ${on === 1 ? "app can" : "apps can"} sign in patrons`) +
    (off ? `, ${off} turned off.` : "."),
  turnedOffGroup: (n: number) => `Turned off (${n})`,
  details: "Details",
  hideDetails: "Hide details",
  typePublic: "Browser or mobile app: no secret needed.",
  typeServer: "Server app: has a secret.",
  addedOn: "Added",
  advanced: "Advanced options",
  nameLabel: "Name",
  urlsLabel: "Redirect URLs",
  urlsHelp: "One per line. Each must match exactly and be https, opds:// or a loopback address.",
  edit: "Edit",
  editTitle: "Edit app",
  editDescription: "Change how this app is set up.",
  save: "Save changes",
  saved: "Saved.",
  savedRevoked: (n: number) => `Saved. ${n} patron ${n === 1 ? "sign-in" : "sign-ins"} ended.`,
  permissionsLabel: "Permissions",
  revokeNote: "Patrons signed in through this app will need to sign in again.",
  saveConfirmTitle: "Save these changes?",
  idReadOnly: "The ID can't be changed because the app already uses it.",
  needUrl: "Add at least one redirect URL.",
  needScope: "Pick at least one permission.",
  resetSecret: "Reset secret",
  resetTitle: (name: string) => `Reset the secret for ${name}?`,
  resetBody: "The old secret stops working right away, and the app's server will need the new one.",
  removeApp: "Remove app",
  removeTitle: (name: string) => `Remove ${name}?`,
  removeBody: "This deletes the app and its sign-ins. It can't be undone, but you can add the app again later.",
  removed: (name: string) => `${name} was removed.`,
  builtInNoRemove: "Built-in apps can't be removed. Turn it off instead.",
  removeHint: "To remove this app, turn it off first.",
  networkError: "Can't reach the server. Check your connection and try again.",
  loadFailed: "Couldn't load your apps.",
  unsupported: "This Lenny server doesn't support App Access yet. Update Lenny, then reload this page.",
  secretTitle: "Copy the client secret now",
  otherNote: "Looking for how patrons log in to Lenny?",
  otherLink: "Patron Sign-in Provider",
} as const

export const SIGN_IN_PROVIDER = {
  route: "/settings/external-auth",
  title: "Patron Sign-in Provider",
  description: "Let patrons sign in with an outside account such as Google or Clerk.",
  otherNote: "Looking for the reading apps that use Lenny?",
  otherLink: APP_ACCESS.title,
} as const
